A_distance = float(input("A distance covered = "))
A_beats_B = float(input(" A beats by B distance = "))
B_distance = (A_distance - A_beats_B)
print(B_distance)
first_race_time_differnce = float(input("first race time difference ="))
other_time_difference = float(input("another race time difference ="))
time_taken_by_A = (first_race_time_differnce*A_distance - B_distance*other_time_difference)/(B_distance -A_distance)
print(f'time taken by A = {time_taken_by_A} sec')
speed_of_A = (A_distance/time_taken_by_A)
speed_of_B = B_distance/(time_taken_by_A+first_race_time_differnce)
print(f'speed of A = {speed_of_A} m/sec')
print(f'speed of B = {speed_of_B} m/sec')